-- modes lib: mode_levels — GENERATED by tools/modes_mapgen; regenerate via scripts/generate_modes_campaign.sh, never hand-edit (cookbook: docs/lua-classpacks-design.md §3).
--
-- Pure data for the mode scripts (og.use("mode_levels")). Fields per level id:
--   mode        "tdm" | "ctf" | "onslaught" | "soccer" | "mutant"
--   teams       active score-team count (team bytes 0..teams-1)
--   time_limit  sim ticks (12/s) the match may run before the mode's
--               time-out rule decides
--   score_limit posted winning score; 0 = the mode's own rule decides
--               (CTF reads the flag stat level; onslaught is
--               elimination)
--   spawn_caps  team byte -> live-spawn cap the mode director enforces
--               on that team's generators (absent = no capped spawns)
--   goal_rects  soccer: team byte -> PIXEL rect {x, y, w, h} of the
--               goal strip that team DEFENDS (matches the painted
--               carpet exactly)
--   kickoff     soccer: kickoff point, PIXEL center of the kickoff
--               tile
local M = {}

M.levels = {
  [300] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 20,
  },
  [301] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 20,
  },
  [302] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 20,
    spawn_caps = {
      [4] = 8,
    },
  },
  [303] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 12,
    spawn_caps = {
      [5] = 4,
      [6] = 4,
    },
  },
  [304] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 10,
    spawn_caps = {
      [7] = 8,
    },
  },
  [305] = {
    mode = "tdm",
    teams = 4,
    time_limit = 7200,
    score_limit = 20,
    spawn_caps = {
      [0] = 4,
      [1] = 4,
      [2] = 4,
      [3] = 4,
    },
  },
  [500] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [501] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [502] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [503] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [504] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [505] = {
    mode = "ctf",
    teams = 3,
    time_limit = 14400,
    score_limit = 0,
  },
  [506] = {
    mode = "ctf",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
  },
  [507] = {
    mode = "ctf",
    teams = 4,
    time_limit = 14400,
    score_limit = 0,
  },
  [508] = {
    mode = "ctf",
    teams = 3,
    time_limit = 14400,
    score_limit = 0,
  },
  [509] = {
    mode = "ctf",
    teams = 4,
    time_limit = 14400,
    score_limit = 0,
  },
  [800] = {
    mode = "onslaught",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
    spawn_caps = {
      [0] = 24,
      [1] = 24,
    },
  },
  [801] = {
    mode = "onslaught",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
    spawn_caps = {
      [0] = 20,
      [1] = 20,
    },
  },
  [802] = {
    mode = "onslaught",
    teams = 3,
    time_limit = 14400,
    score_limit = 0,
    spawn_caps = {
      [0] = 14,
      [1] = 14,
      [2] = 14,
    },
  },
  [803] = {
    mode = "onslaught",
    teams = 2,
    time_limit = 14400,
    score_limit = 0,
    spawn_caps = {
      [0] = 18,
      [1] = 18,
      [7] = 8,
    },
  },
  [820] = {
    mode = "soccer",
    teams = 2,
    time_limit = 10800,
    score_limit = 3,
    goal_rects = {
      [0] = { x = 16, y = 160, w = 32, h = 128 },
      [1] = { x = 656, y = 160, w = 32, h = 128 },
    },
    kickoff = { x = 344, y = 216 },
  },
  [821] = {
    mode = "soccer",
    teams = 2,
    time_limit = 10800,
    score_limit = 3,
    goal_rects = {
      [0] = { x = 16, y = 176, w = 32, h = 128 },
      [1] = { x = 752, y = 176, w = 32, h = 128 },
    },
    kickoff = { x = 392, y = 232 },
  },
  [822] = {
    mode = "soccer",
    teams = 4,
    time_limit = 10800,
    score_limit = 3,
    goal_rects = {
      [0] = { x = 256, y = 16, w = 128, h = 32 },
      [1] = { x = 592, y = 256, w = 32, h = 128 },
      [2] = { x = 256, y = 592, w = 128, h = 32 },
      [3] = { x = 16, y = 256, w = 32, h = 128 },
    },
    kickoff = { x = 312, y = 312 },
  },
  [823] = {
    mode = "soccer",
    teams = 2,
    time_limit = 10800,
    score_limit = 3,
    spawn_caps = {
      [0] = 6,
      [1] = 6,
    },
    goal_rects = {
      [0] = { x = 16, y = 176, w = 32, h = 128 },
      [1] = { x = 688, y = 176, w = 32, h = 128 },
    },
    kickoff = { x = 360, y = 232 },
  },
  [840] = {
    mode = "mutant",
    teams = 4,
    time_limit = 7200,
    score_limit = 10,
  },
  [841] = {
    mode = "mutant",
    teams = 4,
    time_limit = 7200,
    score_limit = 10,
  },
  [842] = {
    mode = "mutant",
    teams = 4,
    time_limit = 7200,
    score_limit = 10,
  },
  [843] = {
    mode = "mutant",
    teams = 4,
    time_limit = 7200,
    score_limit = 10,
  },
}

return M
