-- core:blob — the weapon declaration (cookbook: docs/lua-classpacks-design.md §3).

og.family("weapon", {
  id = "core:blob",
  wire_id = 9,
  name = "BLOB",
  fire_sound = 10,
  skip_sit_notify = false,
  is_auto_attackable = false,
  flags = {},
  init_lifetime = 0,
  init_ani_type = 0,
  vz = 0,
  gravity = 0,
  sizez = 0,
  can_drop_floors = false,
  sprite = og.NIL,
  glyph = "o",
  glyph_ascii = "o",
  glyph_color = "green",
  glyph_bold = false,
  glyph_transparent = false,
  radar_color = "none",
  radar_jitter = 0,
})
