-- core:beast (giant skeleton) — no hooks (cookbook: docs/lua-classpacks-design.md §3).
-- Every behavior-callback slot in the C++ descriptor was null, so this
-- family has no scripted hooks: og.register_hooks with an empty hook table
-- is a load error by design, and registering any hook here would ADD
-- behavior the family never had. Deliberately a no-op chunk.
