-- core:#20 (tower1) — no hooks (cookbook: docs/lua-classpacks-design.md §3).
-- Copyright (C) 1995-2002 FSGames; ported by Sean Ford and Yan Shosh.
--
-- The original loader called tower1 "not *really* a living"; its death
-- switch added "neither do towers" when suppressing bloodspots. Stationary
-- and bloodspot behavior now live in descriptor data.
--
-- This stationary shooter is driven entirely by descriptor data and generic
-- walker/living code, so there is nothing to register here.
-- og.register_hooks with an empty hook table is a load error, so this file
-- deliberately makes no registration call.
--
-- The registry name "BEAST" is shared with ids 18 and 19. core:beast falls
-- back to the first name match (the golem); core:#20 is tower1's exact id.
