/* Multiplayer Game Modes campaign generator — the generated level manifest.
 *
 * Emits tools/modes_mapgen/pack/lib/mode_levels.lua, the og.use("mode_levels")
 * data module the five mode scripts key their per-level registrations off.
 * Generated from the same ExpectedLevel rows that build the maps and drive
 * the self-check, so map content, manifest, and validation cannot drift
 * (single source, D8). The module is COMMITTED (so luals, the statement
 * lint and the coverage inventory see it); the generator hard-fails when
 * the committed copy is stale, rewriting it in place so a rerun passes.
 *
 * Copyright (C) 1995-2002  FSGames. Ported by Sean Ford and Yan Shosh
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */
#include "modes_mapgen.h"

#include <openglad/core/constants.h>

#include <format>
#include <fstream>
#include <sstream>

namespace modesgen {

std::string manifest_lua_text(const std::vector<ExpectedLevel>& rows)
{
    std::ostringstream out;
    out << "-- modes lib: mode_levels — GENERATED by tools/modes_mapgen; "
           "regenerate via scripts/generate_modes_campaign.sh, never "
           "hand-edit (cookbook: docs/lua-classpacks-design.md §3).\n"
        << "--\n"
        << "-- Pure data for the mode scripts (og.use(\"mode_levels\"))."
           " Fields per level id:\n"
        << "--   mode        \"tdm\" | \"ctf\" | \"onslaught\" | \"soccer\""
           " | \"mutant\"\n"
        << "--   teams       active score-team count (team bytes 0.."
           "teams-1)\n"
        << "--   time_limit  sim ticks (12/s) the match may run before the"
           " mode's\n"
        << "--               time-out rule decides\n"
        << "--   score_limit posted winning score; 0 = the mode's own rule"
           " decides\n"
        << "--               (CTF reads the flag stat level; onslaught is\n"
        << "--               elimination)\n"
        << "--   spawn_caps  team byte -> live-spawn cap the mode director"
           " enforces\n"
        << "--               on that team's generators (absent = no capped"
           " spawns)\n"
        << "--   goal_rects  soccer: team byte -> PIXEL rect {x, y, w, h}"
           " of the\n"
        << "--               goal strip that team DEFENDS (matches the"
           " painted\n"
        << "--               carpet exactly)\n"
        << "--   kickoff     soccer: kickoff point, PIXEL center of the"
           " kickoff\n"
        << "--               tile\n"
        << "local M = {}\n"
        << "\n"
        << "M.levels = {\n";
    for (const ExpectedLevel& row : rows)
    {
        out << std::format("  [{}] = {{\n", row.id);
        out << std::format("    mode = \"{}\",\n", mode_name(row.mode));
        out << std::format("    teams = {},\n", row.team_count);
        out << std::format("    time_limit = {},\n", row.time_limit);
        out << std::format("    score_limit = {},\n", row.score_limit);
        if (!row.spawn_caps.empty())
        {
            out << "    spawn_caps = {\n";
            for (const SpawnCap& cap : row.spawn_caps)
                out << std::format("      [{}] = {},\n", cap.team, cap.cap);
            out << "    },\n";
        }
        if (!row.goal_rects.empty())
        {
            out << "    goal_rects = {\n";
            for (std::size_t team = 0; team < row.goal_rects.size(); ++team)
            {
                const GoalRect& g = row.goal_rects[team];
                out << std::format(
                    "      [{}] = {{ x = {}, y = {}, w = {}, h = {} }},\n",
                    team, g.x0 * GRID_SIZE, g.y0 * GRID_SIZE,
                    (g.x1 - g.x0 + 1) * GRID_SIZE,
                    (g.y1 - g.y0 + 1) * GRID_SIZE);
            }
            out << "    },\n";
        }
        if (row.kickoff.tx >= 0)
            out << std::format(
                "    kickoff = {{ x = {}, y = {} }},\n",
                row.kickoff.tx * GRID_SIZE + GRID_SIZE / 2,
                row.kickoff.ty * GRID_SIZE + GRID_SIZE / 2);
        out << "  },\n";
    }
    out << "}\n"
        << "\n"
        << "return M\n";
    return out.str();
}

bool check_and_refresh_manifest(const std::vector<ExpectedLevel>& rows)
{
    const std::string path = "tools/modes_mapgen/pack/lib/mode_levels.lua";
    const std::string fresh = manifest_lua_text(rows);

    std::string committed;
    {
        std::ifstream in(path, std::ios::binary);
        if (in)
        {
            std::ostringstream buf;
            buf << in.rdbuf();
            committed = buf.str();
        }
    }
    if (committed == fresh)
        return true;

    std::ofstream out(path, std::ios::binary);
    out << fresh;
    if (!out)
    {
        fail(std::format("cannot rewrite stale manifest {}", path));
        return false;
    }
    fail(std::format("{} was stale; regenerated in place — rerun the "
                     "generator (regenerate-and-diff discipline)", path));
    return false;
}

} // namespace modesgen
