#!/usr/bin/env bash
#
# Validate the Emscripten game build outputs.
#
# Checks the actual dist/ artifacts produced by the web-emscripten CMake build:
#   1. File existence and minimum sizes (a real game .wasm should be multi-MB)
#   2. WASM binary structure: magic number, version, section headers
#   3. WASM module compilation, exports (must include _main), function count
#   4. JS glue code: syntax validity, Emscripten runtime markers, module loading
#
# Prerequisites:
#   - A completed web-emscripten build (dist/ directory with play.js, play.wasm)
#   - Node.js in PATH
#
# Exit codes:
#   0 = all validations passed
#   1 = one or more validations failed
#   77 = skipped (missing prerequisites)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="${PROJECT_ROOT}/dist"

if ! command -v node >/dev/null 2>&1; then
    echo "SKIP: node not found."
    exit 77
fi

FAIL=0
PASS_COUNT=0

fail() {
    echo "FAIL: $1"
    FAIL=1
}

pass() {
    echo "  PASS: $1"
    PASS_COUNT=$((PASS_COUNT + 1))
}

echo "=== WASM Build Output Validation ==="

# ── 1. File existence and size checks ────────────────────────────────────────

echo ""
echo "--- File existence and size checks ---"

for f in play.js play.wasm; do
    filepath="${DIST_DIR}/${f}"
    if [ ! -f "$filepath" ]; then
        fail "${f} does not exist in dist/"
    elif [ ! -s "$filepath" ]; then
        fail "${f} exists but is empty (zero bytes)"
    else
        size=$(stat -c%s "$filepath" 2>/dev/null || stat -f%z "$filepath" 2>/dev/null)
        pass "${f} exists (${size} bytes)"
    fi
done

# play.html is generated by Emscripten's --shell-file or default shell
if [ -f "${DIST_DIR}/play.html" ]; then
    pass "play.html exists"
else
    echo "  INFO: play.html not found (may be copied separately from web/)"
fi

# The game .wasm binary should be at least 1 MB — a full C++ game with SDL,
# all modules, vendored libs, and game data compiles to several megabytes.
WASM_FILE="${DIST_DIR}/play.wasm"
if [ -f "$WASM_FILE" ]; then
    wasm_size=$(stat -c%s "$WASM_FILE" 2>/dev/null || stat -f%z "$WASM_FILE" 2>/dev/null)
    if [ "$wasm_size" -lt 1000000 ]; then
        fail "play.wasm is only ${wasm_size} bytes — expected >= 1 MB for a full game build"
    else
        wasm_mb=$(awk "BEGIN {printf \"%.1f\", ${wasm_size}/1048576}")
        pass "play.wasm size is ${wasm_mb} MB (${wasm_size} bytes)"
    fi
fi

# The JS glue code should also be substantial (Emscripten runtime + bindings)
JS_FILE="${DIST_DIR}/play.js"
if [ -f "$JS_FILE" ]; then
    js_size=$(stat -c%s "$JS_FILE" 2>/dev/null || stat -f%z "$JS_FILE" 2>/dev/null)
    if [ "$js_size" -lt 50000 ]; then
        fail "play.js is only ${js_size} bytes — expected >= 50 KB for Emscripten glue"
    else
        js_kb=$(awk "BEGIN {printf \"%.0f\", ${js_size}/1024}")
        pass "play.js size is ${js_kb} KB (${js_size} bytes)"
    fi
fi

# ── 2. JS glue code validation ───────────────────────────────────────────────

echo ""
echo "--- JS glue code validation ---"

if [ -f "$JS_FILE" ]; then
    # Syntax check — node --check parses without executing
    if node --check "$JS_FILE" 2>/dev/null; then
        pass "play.js is syntactically valid JavaScript"
    else
        fail "play.js has JavaScript syntax errors"
    fi

    # Check for Emscripten runtime markers that should be present in real glue code
    if grep -q "Module" "$JS_FILE" && grep -q ".wasm" "$JS_FILE"; then
        pass "play.js contains Emscripten Module and .wasm references"
    else
        fail "play.js missing expected Emscripten runtime markers"
    fi
fi

# ── 3. WASM binary validation ────────────────────────────────────────────────

echo ""
echo "--- WASM binary validation ---"

if [ -f "$WASM_FILE" ]; then
    node -e "
const fs = require('fs');

const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
let fail = false;

function PASS(msg) { console.log('  PASS: ' + msg); }
function FAIL(msg) { console.log('FAIL: ' + msg); fail = true; }

// ── Magic number: \\0asm ──
if (bytes[0] === 0x00 && bytes[1] === 0x61 && bytes[2] === 0x73 && bytes[3] === 0x6d) {
    PASS('WASM magic number valid (\\\\0asm)');
} else {
    FAIL('Invalid WASM magic number');
}

// ── Version: must be 1 ──
const version = bytes[4] | (bytes[5] << 8) | (bytes[6] << 16) | (bytes[7] << 24);
if (version === 1) {
    PASS('WASM version is 1');
} else {
    FAIL('Unexpected WASM version: ' + version);
}

// ── Section scan: walk section headers to check structural integrity ──
// WASM sections: 1=Type, 2=Import, 3=Function, 6=Global, 7=Export, 10=Code, 11=Data
const SECTION_NAMES = {
    0:'Custom', 1:'Type', 2:'Import', 3:'Function', 4:'Table', 5:'Memory',
    6:'Global', 7:'Export', 8:'Start', 9:'Element', 10:'Code', 11:'Data',
    12:'DataCount'
};
const sectionsFound = new Set();
let offset = 8; // past header
while (offset < bytes.length) {
    const id = bytes[offset];
    offset++;
    // Read LEB128 section size
    let size = 0, shift = 0;
    while (offset < bytes.length) {
        const b = bytes[offset++];
        size |= (b & 0x7f) << shift;
        if ((b & 0x80) === 0) break;
        shift += 7;
    }
    sectionsFound.add(id);
    offset += size;
}

const requiredSections = [1, 2, 3, 7, 10]; // Type, Import, Function, Export, Code
const missingRequired = requiredSections.filter(s => !sectionsFound.has(s));
if (missingRequired.length === 0) {
    PASS('All required WASM sections present: Type, Import, Function, Export, Code');
} else {
    FAIL('Missing WASM sections: ' + missingRequired.map(s => SECTION_NAMES[s] || s).join(', '));
}

const sectionList = [...sectionsFound].sort((a,b) => a-b).map(s => SECTION_NAMES[s] || ('Unknown(' + s + ')')).join(', ');
console.log('    Sections: ' + sectionList);

// ── WebAssembly.validate ──
if (WebAssembly.validate(bytes)) {
    PASS('WebAssembly.validate() confirms module is valid');
} else {
    FAIL('WebAssembly.validate() rejected the module');
}

// ── Compile and inspect exports ──
WebAssembly.compile(bytes).then(mod => {
    const allExports = WebAssembly.Module.exports(mod);
    const allImports = WebAssembly.Module.imports(mod);
    PASS('WASM module compiled successfully');

    const funcExports = allExports.filter(e => e.kind === 'function');
    const memExports = allExports.filter(e => e.kind === 'memory');
    const tableExports = allExports.filter(e => e.kind === 'table');

    console.log('    Total exports: ' + allExports.length + ' (' + funcExports.length + ' functions, ' + memExports.length + ' memory, ' + tableExports.length + ' table)');
    console.log('    Total imports: ' + allImports.length);

    // A real game build should export many functions
    if (funcExports.length >= 10) {
        PASS('Module exports ' + funcExports.length + ' functions (game-scale)');
    } else if (funcExports.length > 0) {
        FAIL('Module only exports ' + funcExports.length + ' functions — expected >= 10 for a game build');
    } else {
        FAIL('Module exports zero functions');
    }

    // _main is the Emscripten entry point for a C/C++ program
    const hasMain = funcExports.some(e => e.name === 'main' || e.name === '_main');
    if (hasMain) {
        PASS('Module exports _main entry point');
    } else {
        FAIL('Module does not export _main — Emscripten game build should have a main()');
    }

    // Check for memory export (Emscripten typically exports 'memory')
    if (memExports.length > 0) {
        PASS('Module exports memory');
    } else {
        console.log('  INFO: No memory export (may be imported instead)');
    }

    // Print a sample of exported function names for debugging
    const sampleNames = funcExports.slice(0, 10).map(e => e.name);
    if (funcExports.length > 10) {
        sampleNames.push('... and ' + (funcExports.length - 10) + ' more');
    }
    console.log('    Sample exports: ' + sampleNames.join(', '));

    if (fail) process.exit(1);
}).catch(err => {
    FAIL('Could not compile WASM module: ' + err.message);
    process.exit(1);
});
" "$WASM_FILE"
    if [ $? -ne 0 ]; then
        fail "WASM binary validation failed"
    fi
fi

# ── 4. JS glue module loading test ───────────────────────────────────────────

echo ""
echo "--- JS glue module loading test ---"

if [ -f "$JS_FILE" ] && [ -f "$WASM_FILE" ]; then
    # Try to load the Emscripten JS in node. The game will fail to initialize
    # SDL/graphics (no browser), but the JS runtime and WASM module should load
    # successfully before hitting that point. We run with a timeout and look
    # for signs of successful module loading vs. a JS-level crash.
    LOAD_OUTPUT=$(cd "$DIST_DIR" && timeout 10 node -e "
// Suppress Emscripten's process.exit() calls so we can inspect how far it got
const origExit = process.exit;
let exitCode = null;
process.exit = function(code) { exitCode = code; };

// Emscripten expects a global Module object; provide minimal stubs
globalThis.Module = {
    noInitialRun: true,
    print: function() {},
    printErr: function() {},
    onAbort: function(what) {
        console.log('MODULE_ABORT: ' + what);
    },
    onRuntimeInitialized: function() {
        console.log('RUNTIME_INITIALIZED');
    }
};

try {
    require('./play.js');
    // Give async init a moment to run
    setTimeout(function() {
        console.log('JS_LOADED_OK');
        origExit(0);
    }, 2000);
} catch (e) {
    console.log('JS_LOAD_ERROR: ' + e.message);
    origExit(1);
}
" 2>&1) || true

    if echo "$LOAD_OUTPUT" | grep -q "JS_LOADED_OK\|RUNTIME_INITIALIZED"; then
        pass "Emscripten JS glue loads and begins initialization in Node.js"
        if echo "$LOAD_OUTPUT" | grep -q "RUNTIME_INITIALIZED"; then
            pass "Emscripten runtime fully initialized (WASM module loaded)"
        fi
    elif echo "$LOAD_OUTPUT" | grep -q "JS_LOAD_ERROR"; then
        error_msg=$(echo "$LOAD_OUTPUT" | grep "JS_LOAD_ERROR" | head -1)
        fail "JS glue failed to load: ${error_msg}"
    else
        # Even a timeout or SDL error is OK — it means the JS parsed and started
        echo "  INFO: JS glue started but did not complete init (expected without SDL)"
        echo "  INFO: Output: $(echo "$LOAD_OUTPUT" | head -3)"
        pass "Emscripten JS glue is loadable (started execution in Node.js)"
    fi
fi

# ── Final result ──────────────────────────────────────────────────────────────

echo ""
echo "=== Results: ${PASS_COUNT} checks passed, ${FAIL} failures ==="
if [ "$FAIL" -eq 0 ]; then
    echo "=== All WASM build output validations passed ==="
    exit 0
else
    echo "=== WASM build output validation FAILED ==="
    exit 1
fi
