CFLAGS=-g `sdl-config --libs --cflags` -lSDL_mixer
GLADFILES=button.o effect.o game.o glad.o gladpack.o graphlib.o guy.o help.o intro.o living.o loader.o obmap.o pal32.o parser.o picker.o pixie.o pixien.o radar.o screen.o smooth.o sound.o stats.o text.o treasure.o video.o view.o walker.o weap.o input.o sai2x.o
SCENFILES=scen.o effect.o game.o gladpack.o graphlib.o guy.o help.o intro.o living.o loader.o obmap.o pal32.o parser.o pixie.o pixien.o radar.o screen.o smooth.o sound.o stats.o text.o treasure.o video.o view.o walker.o weap.o input.o sai2x.o


all: openglad


openglad: $(GLADFILES)
	g++ $(CFLAGS) -o ../openglad $(GLADFILES)

openscen: $(SCENFILES)
	g++ $(CFLAGS) -DOPENSCEN -o ../openscen $(SCENFILES)

clean:
	rm -f *.o
	rm -f ../openglad
	rm -f ../openscen

.cpp.o:
	g++ -g -c -I./ -I/usr/include/SDL $<
